// Generated by gencpp from file evaotonom/sign.msg
// DO NOT EDIT!


#ifndef EVAOTONOM_MESSAGE_SIGN_H
#define EVAOTONOM_MESSAGE_SIGN_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace evaotonom
{
template <class ContainerAllocator>
struct sign_
{
  typedef sign_<ContainerAllocator> Type;

  sign_()
    : integer_value(0)
    , float_value(0.0)  {
    }
  sign_(const ContainerAllocator& _alloc)
    : integer_value(0)
    , float_value(0.0)  {
  (void)_alloc;
    }



   typedef int8_t _integer_value_type;
  _integer_value_type integer_value;

   typedef float _float_value_type;
  _float_value_type float_value;





  typedef boost::shared_ptr< ::evaotonom::sign_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::evaotonom::sign_<ContainerAllocator> const> ConstPtr;

}; // struct sign_

typedef ::evaotonom::sign_<std::allocator<void> > sign;

typedef boost::shared_ptr< ::evaotonom::sign > signPtr;
typedef boost::shared_ptr< ::evaotonom::sign const> signConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::evaotonom::sign_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::evaotonom::sign_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::evaotonom::sign_<ContainerAllocator1> & lhs, const ::evaotonom::sign_<ContainerAllocator2> & rhs)
{
  return lhs.integer_value == rhs.integer_value &&
    lhs.float_value == rhs.float_value;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::evaotonom::sign_<ContainerAllocator1> & lhs, const ::evaotonom::sign_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace evaotonom

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::evaotonom::sign_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::evaotonom::sign_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::evaotonom::sign_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::evaotonom::sign_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::evaotonom::sign_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::evaotonom::sign_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::evaotonom::sign_<ContainerAllocator> >
{
  static const char* value()
  {
    return "86552f94e8d05479ea1a2f8469e502c6";
  }

  static const char* value(const ::evaotonom::sign_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x86552f94e8d05479ULL;
  static const uint64_t static_value2 = 0xea1a2f8469e502c6ULL;
};

template<class ContainerAllocator>
struct DataType< ::evaotonom::sign_<ContainerAllocator> >
{
  static const char* value()
  {
    return "evaotonom/sign";
  }

  static const char* value(const ::evaotonom::sign_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::evaotonom::sign_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 integer_value\n"
"float32 float_value\n"
;
  }

  static const char* value(const ::evaotonom::sign_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::evaotonom::sign_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.integer_value);
      stream.next(m.float_value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct sign_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::evaotonom::sign_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::evaotonom::sign_<ContainerAllocator>& v)
  {
    s << indent << "integer_value: ";
    Printer<int8_t>::stream(s, indent + "  ", v.integer_value);
    s << indent << "float_value: ";
    Printer<float>::stream(s, indent + "  ", v.float_value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EVAOTONOM_MESSAGE_SIGN_H
