// Generated by gencpp from file evaotonom/Sign.msg
// DO NOT EDIT!


#ifndef EVAOTONOM_MESSAGE_SIGN_H
#define EVAOTONOM_MESSAGE_SIGN_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace evaotonom
{
template <class ContainerAllocator>
struct Sign_
{
  typedef Sign_<ContainerAllocator> Type;

  Sign_()
    : sign_index(0)
    , depth(0.0)  {
    }
  Sign_(const ContainerAllocator& _alloc)
    : sign_index(0)
    , depth(0.0)  {
  (void)_alloc;
    }



   typedef int8_t _sign_index_type;
  _sign_index_type sign_index;

   typedef float _depth_type;
  _depth_type depth;





  typedef boost::shared_ptr< ::evaotonom::Sign_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::evaotonom::Sign_<ContainerAllocator> const> ConstPtr;

}; // struct Sign_

typedef ::evaotonom::Sign_<std::allocator<void> > Sign;

typedef boost::shared_ptr< ::evaotonom::Sign > SignPtr;
typedef boost::shared_ptr< ::evaotonom::Sign const> SignConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::evaotonom::Sign_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::evaotonom::Sign_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::evaotonom::Sign_<ContainerAllocator1> & lhs, const ::evaotonom::Sign_<ContainerAllocator2> & rhs)
{
  return lhs.sign_index == rhs.sign_index &&
    lhs.depth == rhs.depth;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::evaotonom::Sign_<ContainerAllocator1> & lhs, const ::evaotonom::Sign_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace evaotonom

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::evaotonom::Sign_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::evaotonom::Sign_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::evaotonom::Sign_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::evaotonom::Sign_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::evaotonom::Sign_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::evaotonom::Sign_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::evaotonom::Sign_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9d6f7ebc229c76b7f8002caeee511826";
  }

  static const char* value(const ::evaotonom::Sign_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9d6f7ebc229c76b7ULL;
  static const uint64_t static_value2 = 0xf8002caeee511826ULL;
};

template<class ContainerAllocator>
struct DataType< ::evaotonom::Sign_<ContainerAllocator> >
{
  static const char* value()
  {
    return "evaotonom/Sign";
  }

  static const char* value(const ::evaotonom::Sign_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::evaotonom::Sign_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 sign_index\n"
"float32 depth\n"
;
  }

  static const char* value(const ::evaotonom::Sign_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::evaotonom::Sign_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sign_index);
      stream.next(m.depth);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Sign_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::evaotonom::Sign_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::evaotonom::Sign_<ContainerAllocator>& v)
  {
    s << indent << "sign_index: ";
    Printer<int8_t>::stream(s, indent + "  ", v.sign_index);
    s << indent << "depth: ";
    Printer<float>::stream(s, indent + "  ", v.depth);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EVAOTONOM_MESSAGE_SIGN_H
